# clash改动版本
# 日期：2024-12.31
# 配置说明：https://github.com/MetaCubeX/mihomo/blob/Alpha/docs/config.yaml
# 原配置作者：https://github.com/Rabbit-Spec
# 适用版本：所有使用 Mihomo 内核的程序

port: 7890
socks-port: 7891
mixed-port: 7892
redir-port: 7893
tproxy-port: 7894

unified-delay: true
tcp-concurrent: true
find-process-mode: strict
global-client-fingerprint: chrome

allow-lan: true
mode: rule
log-level: info
ipv6: true
udp: true

external-controller: 0.0.0.0:9090
# external-ui: ui
# external-ui-url: 'https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip'

geodata-mode: false
geodata-loader: standard
geo-auto-update: true # 是否自动更新 geodata
geo-update-interval: 24 # 更新间隔，单位：小时
geox-url:
  geoip: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/release/geoip.dat'
  geosite: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/release/geosite.dat'
  mmdb: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/release/geoip.metadb'
  asn: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/release/GeoLite2-ASN.mmdb'

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - +.v2ex.com

  # skip-domain:

tun:
  enable: true
  stack: mixed
  dns-hijack:
    - any:53
  auto-route: true
  auto-detect-interface: true

dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    #- "*"
    - "+.lan"
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.114
    - 8.8.8.8
  nameserver:
    - 114.114.114.114 # default value
    - 8.8.8.8 # default value
    - https://223.5.5.5/dns-query#h3=true
    - https://223.6.6.6/dns-query#h3=true

# 锚点 - 节点订阅的参数 [每24小时更新一次订阅节点，# 每 60 秒一次健康检查]
NodeParam: &NodeParam {type: http, interval: 86400} # , health-check: {enable: true, url: 'http://www.google.com/generate_204', interval: 300}}

# 锚点 - 节点订阅
proxy-providers: 
  我的节点:
    url: '机场的订阅地址'
    <<: *NodeParam
    path: './proxy_provider/Providers.yaml'

# 锚点 - 节点筛选组
All: &All {type: select, proxies: [🚀 手动切换, 🇭🇰 香港节点, 🇨🇳 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇬🇧 英国节点, 🇩🇪 德国节点, 🏳️‍🌈 其他节点, 1️⃣NET 1, 2️⃣NET 2, 3️⃣NET 3, 4️⃣NET 4, DIRECT]}
FilterHK: &FilterHK '香港|Hong Kong|HK|HongKong|hongkong|HKG|港'
FilterJP: &FilterJP 'japan|JPN|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|日|JP|Japan'
FilterTW: &FilterTW '台湾|台灣|Tai Wan|TWN|台|新北|彰化|TW|Taiwan'
FilterKR: &FilterKR '韩国|韓國|korea|South Korea|SouthKorea|KR|Korea|KOR|首尔|韩|韓'
FilterSG: &FilterSG 'singgapore|新加坡|坡|狮城|SGP|SG|Singapore'
FilterUS: &FilterUS '美|美國|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|USA|United States|UnitedStates'
FilterUK: &FilterUK 'United Kingdom|英|伦敦|UK|Britain'
FilterDE: &FilterDE 'Germany|Berlin|DEU|德|Frankfurt|法兰克福|柏林'
FilterOther: &FilterOther '^(?!.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|日|JP|Japan))(?!.*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|USA|United States))(?!.*(KR|Korea|KOR|首尔|韩|韓))(?!.*(United Kingdom|英|伦敦|UK|Britain))(?!.*(Germany|Berlin|DEU|德|Frankfurt|法兰克福|柏林))(?!.*(新加坡|坡|狮城|SGP|Singapore))(?!.*(台|新北|彰化|TW|Taiwan))(?!.*(港|HK|Hong Kong))(?!.*(时间|剩余)).*'

# FilterAll: &FilterAll '^(?=.*(.))(?!.*((?i)群|邀请|返利|循环|官网|客服|网站|网址|获取|订阅|流量|到期|机场|下次|版本|官址|备用|过期|已用|联系|邮箱|工单|贩卖|通知|倒卖|防止|国内|地址|频道|无法|说明|使用|提示|特别|访问|支持|教程|关注|更新|作者|加入|(\b(USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author)\b|(\d{4}-\d{2}-\d{2}|\d+G)))).*$'

# 锚点 - 故障转移参数 [每 10 秒一次惰性健康检查，时延超过 2 秒判定为失败，失败 3 次则自动触发健康检查]
# FallBack: &FallBack {type: fallback, interval: 10, lazy: true, url: 'http://www.google.com/generate_204', disable-udp: false, timeout: 2000, max-failed-times: 3, hidden: true, include-all-providers: true}


proxies:
 - name: "direct"
   type: direct
   udp: true

# 策略组
proxy-groups: 
  - {name: 🚀 节点选择, type: select, proxies: [🚀 手动切换, 🇭🇰 香港节点, 🇨🇳 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇬🇧 英国节点, 🇩🇪 德国节点, 🏳️‍🌈 其他节点, DIRECT]}

  - {name: 🇭🇰 香港节点, type: select, <<: filter: *FilterHK}
  - {name: 🇯🇵 日本节点, type: select, <<: filter: *FilterJP}
  - {name: 🇨🇳 台湾节点, type: select, <<: filter: *FilterTW}
  - {name: 🇰🇷 韩国节点, type: select, <<: filter: *FilterKR}
  - {name: 🇸🇬 新加坡节点, type: select, <<: filter: *FilterSG}
  - {name: 🇺🇸 美国节点, type: select, <<: filter: *FilterUS}
  - {name: 🇬🇧 英国节点, type: select, <<: filter: *FilterUK}
  - {name: 🇩🇪 德国节点, type: select, <<: filter: *FilterDE}
  - {name: 🇩🇪 🏳️‍🌈 其他节点, type: select, <<: filter: *FilterOther}
  - {name: 1️⃣NET 1, type: select, ^(?!.*(时间|剩余)).*}
  - {name: 2️⃣NET 2, type: select, ^(?!.*(时间|剩余)).*}
  - {name: 3️⃣NET 3, type: select, ^(?!.*(时间|剩余)).*}
  - {name: 4️⃣NET 4, type: select, ^(?!.*(时间|剩余)).*}

  - {name: 📷 TikTok, <<: *All}
  - {name: 🎥 Netflix, <<: *All}
  - {name: 📲 Telegram,  <<: *All}
  - {name: 📺 Twitch, <<: *All}
  - {name: 🎙 Discord, <<: *All}
  - {name: 📹 YouTube, <<: *All}
  - {name: 🦄 Disney, <<: *All}
  - {name: 🍻 哔哩哔哩, <<: *All}
  - {name: 🌍 国外媒体, <<: *All}
  - {name: 🌏 国内媒体, <<: *All}
  - {name: 🗾 日本媒体, <<: *All}
  - {name: ⏳ 各测速网站, <<: *All}
  - {name: 📢 Google, <<: *All}
  - {name: Ⓜ️ 微软云盘, <<: *All}
  - {name: Ⓜ️ 微软服务, <<: *All}
  - {name: 🍎 Apple, <<: *All}
  - {name: 🎮 Steam, <<: *All}
  - {name: 🎯 全球直连, <<: *All}
  - {name: ₿ 交易所, <<: *All}
  - {name: 💲 PayPal, <<: *All}
  - {name: 💳 Redotpay, <<: *All}
  - {name: ♾️ customize_oversea, <<: *All}
  - {name: ♾️ customize_domestic, <<: *All}
  - {name: ©️ PT&BT, <<: *All}
  - {name: ©️ Emby, <<: *All}
  - {name: 🐟 漏网之鱼, <<: *All}
  - {name: 🆎 AdBlock, type: select, proxies: [🚀 手动切换, 🇭🇰 香港节点, 🇨🇳 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇺🇲 美国节点, 🇬🇧 英国节点, 🇩🇪 德国节点, 🏳️‍🌈 其他节点, 1️⃣NET 1, 2️⃣NET 2, 3️⃣NET 3, 4️⃣NET 4, DIRECT, REJECT]}


# 锚点 - 规则参数 [每天更新一次订阅规则，更新规则时使用直连策略]
RuleSet: &RuleSet {type: http, behavior: classical, interval: 86400, format: yaml, proxy: DIRECT}

# 订阅规则
rule-providers:
  测速网站:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/Moriarty-989/listes/master/Clash/Ruleset/Speedtest.list'
    path: './RuleSet/测速网站.yaml'

  AdBlock:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list'
    path: './RuleSet/AdBlock.yaml'
  AdBlock1:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list'
    path: './RuleSet/AdBlock1.yaml'
  AdBlock2:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list'
    path: './RuleSet/AdBlock2.yaml'
  AdBlock3:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list'
    path: './RuleSet/AdBlock3.yaml'
  AdBlock4:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list'
    path: './RuleSet/AdBlock4.yaml'

  customize_oversea:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/wakaka0230/rules.conf/main/rules/customize_oversea'
    path: './RuleSet/customize_oversea.yaml'

  customize_domestic:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/wakaka0230/rules.conf/main/rules/customize_domestic'
    path: './RuleSet/customize_domestic.yaml'

  Telegram:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list'
    path: './RuleSet/Telegram.yaml'

  Discord:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Discord/Discord.list'
    path: './RuleSet/Discord.yaml'

  Steam:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.list'
    path: './RuleSet/Steam.yaml'
  Steam1:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/wakaka0230/rules.conf/main/rules/steam'
    path: './RuleSet/Steam1.yaml'

  Binance:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Binance/Binance.list'
    path: './RuleSet/Binance.yaml'
  OKX:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OKX/OKX.list'
    path: './RuleSet/OKX.yaml'
  OKX1:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix_Classical_No_Resolve.yaml'
    path: './RuleSet/OKX1.yaml'
  Metamask:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/wakaka0230/rules.conf/main/rules/Metamask'
    path: './RuleSet/Metamask.yaml'
  Binance1:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/wakaka0230/rules.conf/main/rules/Binance'
    path: './RuleSet/Binance1.yaml'
  Trustwallet:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/wakaka0230/rules.conf/main/rules/Trustwallet'
    path: './RuleSet/Trustwallet.yaml'
  Bybit:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/wakaka0230/rules.conf/main/rules/Bybit'
    path: './RuleSet/Bybit.yaml'

  PayPal:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PayPal/PayPal.list'
    path: './RuleSet/PayPal.yaml'

  Redotpay:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/wakaka0230/rules.conf/main/rules/Redotpay'
    path: './RuleSet/Redotpay.yaml'

  哔哩哔哩:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.list'
    path: './RuleSet/哔哩哔哩.yaml'

  YouTube:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list'
    path: './RuleSet/YouTube.yaml'

  Netflix:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list'
    path: './RuleSet/Netflix.yaml'

  TikTok:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list'
    path: './RuleSet/TikTok.yaml'

  Twitch:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitch/Twitch.list'
    path: './RuleSet/Twitch.yaml'

  Google:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleSearch/GoogleSearch.list'
    path: './RuleSet/Google.yaml'
  Google1:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleVoice/GoogleVoice.list'
    path: './RuleSet/Google1.yaml'
  Google2:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list'
    path: './RuleSet/Google2.yaml'
  Google3:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list'
    path: './RuleSet/Google3.yaml'


  Apple:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list'
    path: './RuleSet/Apple.yaml'

  微软云盘:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.list'
    path: './RuleSet/微软云盘.yaml'
  
  微软服务:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list'
    path: './RuleSet/微软服务.yaml'

  国内媒体:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list'
    path: './RuleSet/国内媒体.yaml'

  日本媒体:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Niconico/Niconico.list'
    path: './RuleSet/日本媒体.yaml'
  日本媒体1:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AbemaTV/AbemaTV.list'
    path: './RuleSet/日本媒体1.yaml'
  日本媒体2:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HuluJP/HuluJP.list'
    path: './RuleSet/日本媒体2.yaml'
  日本媒体3:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/DMM/DMM.list'
    path: './RuleSet/日本媒体3.yaml'
  日本媒体4:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/HotKids/Rules/master/Quantumult/X/Filter/U-NEXT.list'
    path: './RuleSet/日本媒体4.yaml'

  国外媒体:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list'
    path: './RuleSet/国外媒体.yaml'

  PT&BT:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PrivateTracker/PrivateTracker.list'
    path: './RuleSet/日本媒体1.yaml'

  Emby:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/wakaka0230/rules.conf/main/rules/Emby'
    path: './RuleSet/Emby.yaml'

  节点选择:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Instagram/Instagram.list'
    path: './RuleSet/节点选择.yaml'
  节点选择1:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Facebook/Facebook.list'
    path: './RuleSet/节点选择1.yaml'
  节点选择2:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.list'
    path: './RuleSet/节点选择2.yaml'
  节点选择3:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Wikimedia/Wikimedia.list'
    path: './RuleSet/节点选择3.yaml'
  节点选择4:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list'
    path: './RuleSet/节点选择4.yaml'
  节点选择5:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Reddit/Reddit.list'
    path: './RuleSet/节点选择5.yaml'
  节点选择6:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Notion/Notion.list'
    path: './RuleSet/节点选择6.yaml'
  节点选择7:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/wakaka0230/rules.conf/main/rules/US-MAIN'
    path: './RuleSet/节点选择7.yaml'
  节点选择8:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list'
    path: './RuleSet/节点选择8.yaml'

  全球直连:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list'
    path: './RuleSet/全球直连.yaml'
  全球直连1:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list'
    path: './RuleSet/全球直连1.yaml'
  全球直连2:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list'
    path: './RuleSet/全球直连2.yaml'
  全球直连3:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list'
    path: './RuleSet/全球直连3.yaml'
  全球直连4:
    <<: *RuleSet
    url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list'
    path: './RuleSet/全球直连4.yaml'


# 分流规则指向
rules:
 - RULE-SET,测速网站,⏳ 各测速网站
 - RULE-SET,AdBlock,🆎 AdBlock
 - RULE-SET,AdBlock1,🆎 AdBlock
 - RULE-SET,AdBlock2,🆎 AdBlock
 - RULE-SET,AdBlock3,🆎 AdBlock
 - RULE-SET,AdBlock4,🆎 AdBlock
 - RULE-SET,customize_oversea,♾️ customize_oversea
 - RULE-SET,customize_domestic,♾️ customize_domestic
 - RULE-SET,Telegram,📲 Telegram
 - RULE-SET,Discord,🎙 Discord
 - RULE-SET,Steam,🎮 Steam
 - RULE-SET,Steam1,🎮 Steam
 - RULE-SET,Binance,₿ 交易所
 - RULE-SET,Binance1,₿ 交易所
 - RULE-SET,OKX,₿ 交易所
 - RULE-SET,OKX1,₿ 交易所
 - RULE-SET,Metamask,₿ 交易所
 - RULE-SET,Trustwallet,₿ 交易所
 - RULE-SET,Bybit,₿ 交易所
 - RULE-SET,PayPal,💲 PayPal
 - RULE-SET,Redotpay,💳 Redotpay
 - RULE-SET,哔哩哔哩,🍻 哔哩哔哩
 - RULE-SET,YouTube,📹 YouTube
 - RULE-SET,Netflix,🎥 Netflix
 - RULE-SET,TikTok,📷 TikTok
 - RULE-SET,Twitch,📺 Twitch
 - RULE-SET,Google,📢 Google
 - RULE-SET,Google1,📢 Google
 - RULE-SET,Google2,📢 Google
 - RULE-SET,Google3,📢 Google
 - RULE-SET,Apple,🍎 Apple
 - RULE-SET,微软云盘,Ⓜ️ 微软云盘
 - RULE-SET,微软服务,Ⓜ️ 微软服务
 - RULE-SET,国内媒体,🌏 国内媒体
 - RULE-SET,日本媒体,🗾 日本媒体
 - RULE-SET,日本媒体1,🗾 日本媒体
 - RULE-SET,日本媒体2,🗾 日本媒体
 - RULE-SET,日本媒体3,🗾 日本媒体
 - RULE-SET,日本媒体4,🗾 日本媒体
 - RULE-SET,国外媒体,🌍 国外媒体
 - RULE-SET,PT&BT,©️ PT&BT
 - RULE-SET,Emby,©️ Emby
 - RULE-SET,节点选择,🚀 节点选择
 - RULE-SET,节点选择1,🚀 节点选择
 - RULE-SET,节点选择2,🚀 节点选择
 - RULE-SET,节点选择3,🚀 节点选择
 - RULE-SET,节点选择4,🚀 节点选择
 - RULE-SET,节点选择5,🚀 节点选择
 - RULE-SET,节点选择6,🚀 节点选择
 - RULE-SET,节点选择7,🚀 节点选择
 - RULE-SET,节点选择8,🚀 节点选择
 - RULE-SET,全球直连,🎯 全球直连
 - RULE-SET,全球直连1,🎯 全球直连
 - RULE-SET,全球直连2,🎯 全球直连
 - RULE-SET,全球直连3,🎯 全球直连
 - RULE-SET,全球直连4,🎯 全球直连

 - GEOIP,CN,DIRECT
 - MATCH,🐟 漏网之鱼
